### ISSUE TITLE
 Add the CalendarViewAppeared action

### ISSUE THREAD

**Issue by juanlaube** [toggl/android#269]
## Description

Add the CalendarViewAppeared action and handle it in the reducer. This action should create an effect to fetch the visible calendar items from the calendar service.

## Definition of done
- [ ] The `FetchCalendarEventsEffect` is dispatched and handled
- [ ] The state is updated with the fetched calendar events
- [ ] Tests are created
Make sure it's tested

Depends on #267

**Comment by semanticer** [comment]
@juanlaube I think you forgot to mention `CalendarEventsFetched` action that should be emitted from `FetchCalendarEventsEffect`.

**Comment by semanticer** [comment]
@juanlaube 
I think `CalendarService` should return `flow` because access to calendar events won't be synchronous I think. 
```kotlin
fun getCalendarEvents(
        fromStartDate: OffsetDateTime,
        toEndDate: OffsetDateTime,
        fromCalendars: List<Calendar>
): Flow<List<CalendarEvent>>
```

Also, you say:

> ... fetch the visible calendar items from the calendar service.

To fetching visible items I need to provide correct arguments for `fromStartDate`,  `toEndDate` and `fromCalendars`. We don't know any of these values at this point, should I add them to `CalendarState` or maybe we are doing this issue too early?

**Comment by juanlaube** [comment]
@semanticer yes, that's a good point, if the calendar api is async then lets make the calendar service async too.
